// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjbMJ-2d_Wjr9XBe8u8HPo0cShVLU7isA',
    appId: '1:892705507147:web:11a76e6e84795bc7010ace',
    messagingSenderId: '892705507147',
    projectId: 'capiznon-language-app-7938d',
    authDomain: 'capiznon-language-app-7938d.firebaseapp.com',
    storageBucket: 'capiznon-language-app-7938d.firebasestorage.app',
    measurementId: 'G-B2XPRQREV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBry_0_ocFtk0i-12IzRPTxUHhm3JWCwp4',
    appId: '1:892705507147:android:51f79e2b64090843010ace',
    messagingSenderId: '892705507147',
    projectId: 'capiznon-language-app-7938d',
    storageBucket: 'capiznon-language-app-7938d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwnz-ztMKzm_SSz0-shiG2fZwRhhXhWf0',
    appId: '1:892705507147:ios:43830e69ee9f356b010ace',
    messagingSenderId: '892705507147',
    projectId: 'capiznon-language-app-7938d',
    storageBucket: 'capiznon-language-app-7938d.firebasestorage.app',
    iosBundleId: 'com.example.languageGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwnz-ztMKzm_SSz0-shiG2fZwRhhXhWf0',
    appId: '1:892705507147:ios:43830e69ee9f356b010ace',
    messagingSenderId: '892705507147',
    projectId: 'capiznon-language-app-7938d',
    storageBucket: 'capiznon-language-app-7938d.firebasestorage.app',
    iosBundleId: 'com.example.languageGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjbMJ-2d_Wjr9XBe8u8HPo0cShVLU7isA',
    appId: '1:892705507147:web:d2c2612b4245bde2010ace',
    messagingSenderId: '892705507147',
    projectId: 'capiznon-language-app-7938d',
    authDomain: 'capiznon-language-app-7938d.firebaseapp.com',
    storageBucket: 'capiznon-language-app-7938d.firebasestorage.app',
    measurementId: 'G-V2EWW7EZDM',
  );
}
